### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#210]
To avoid opening so many issues, I am going to post my to-do items for this repository here.

I have closed all the unnecessary issues.

To Compile and/or Package
- [ ] `transfersh` [link](https://github.com/raspbian-addons/raspbian-addons/issues/154)
- [ ] `tuner` [link](https://github.com/raspbian-addons/raspbian-addons/issues/157)
- [ ] `fondo` [link](https://github.com/raspbian-addons/raspbian-addons/issues/193)
- [ ] `obs-studio:arm64` [link](https://github.com/raspbian-addons/raspbian-addons/issues/171)
- [ ] `mockoon` [link](https://github.com/raspbian-addons/raspbian-addons/issues/54)

To Add to [Autoupdate](https://github.com/raspbian-addons/autoupdate)
- [ ] 

Other Tasks
- [ ] Automatic repository backup, maybe using a local script instead of GitHub Actions.

**Comment by Itai-Nelken** [comment]
You can also use the 'Projects' feature to create todo lists.
